name: Build postmarketOS
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y python3-pip git
      - name: Install pmbootstrap
        run: pip3 install --user pmbootstrap
      - name: Build
        run: |
          echo -e "samsung-a2corelte\nnone\nn\nn\n" | ~/.local/bin/pmbootstrap init
          ~/.local/bin/pmbootstrap install --password 12345678 --no-fde
      - name: Export
        run: |
          ~/.local/bin/pmbootstrap export
          mkdir -p out
          cp -r /tmp/postmarketOS-export/* out/ || true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: pmos-a2corelte
          path: out/
